
platform :ios, '12.0'
use_frameworks!
use_modular_headers!

flutter_root = '/Users/shubhampawar/Developer/flutter'
require File.expand_path('packages/flutter_tools/bin/podhelper', flutter_root)


target 'Runner' do
  flutter_install_all_ios_pods(File.dirname(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      # Enable ARC for all pods
      config.build_settings['CLANG_ENABLE_OBJC_ARC'] = 'YES'
    end
  end
end
